---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ProjectName:
    Type: String
    Description: The name of the CodeBuild project

  RepoArn:
    Type: String
    Description: |
      The ARN of the CodeCommit repository CodeBuild will build from. Leave the
      default value if you are not using CodeCommit.
    Default: arn:aws:codecommit:unused::UNUSED

  RepoUrl:
    Description: |
      The location of the source code. This will normally be the HTTPS (*not
      HTTPS-GRC*) URL of the CodeCommit repository. If you are using something
      other than CodeCommit, see [AWS::CodeBuild::Project Source - Location](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html#cfn-codebuild-project-source-location).
    Type: String

  EnvType:
    Type: String
    Description: |
      The type of environment the builds will occur in. For a list of supported
      values, see [AWS::CodeBuild::Project Environment - Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html#cfn-codebuild-project-environment-type).
    Default: LINUX_CONTAINER

  EnvImage:
    Type: String
    Description: |
      The image tag or image digest that identifies the Docker image to use for
      this build project. Banner application builds will typically use the
      current x86_64 Amazon Linux 2 image (ex.
      `aws/codebuild/amazonlinux2-x86_64-standard:3.0`.) Amazon provides
      [a set of standard images](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html).

  EnvComputeType:
    Type: String
    Description: |
      The type of compute environment. This determines the number of CPU cores
      and memory the build environment uses. For a list of supported values, see
      [AWS::CodeBuild::Project Environment - ComputeType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html#cfn-codebuild-project-environment-computetype)
    Default: BUILD_GENERAL1_SMALL

  ArtifactBucket:
    Type: String
    Description: |
      The name of an S3 bucket used for build resources. If your project
      produces artifacts, they will be stored here.

  SourceType:
    Type: String
    Description: |
      The type of repository that contains the source code to be built. For a
      list of supported values, see [AWS::CodeBuild::Project Source - Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html#cfn-codebuild-project-source-type).
    Default: CODECOMMIT

  BuildSpec:
    Type: String
    Description: The relative path within the source repository for the project's build specification.
    Default: "buildspec.yml"

  DefaultRevision:
    Type: String
    Description: Default value for the `REVISION` environment variable.
    Default: "1.0-SNAPSHOT"

  CreatesDockerImage:
    Type: String
    Description: Set this to `"true"` to create an ECR repository and related resources.
    Default: "false"

  ExtraEnvVar1:
    Type: String
    Description: The name of an extra environment variable available during the build.
    Default: "EXTRA_ARG_1"

  ExtraEnvVal1:
    Type: String
    Description: The default value of this environment variable.
    Default: ""

  ExtraEnvType1:
    Type: String
    Description: |
      The type of this environment variable. For a list of supported values, see
      [AWS::CodeBuild::Project EnvironmentVariable - Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environmentvariable.html#cfn-codebuild-project-environmentvariable-type).
    Default: PLAINTEXT

  ExtraEnvVar2:
    Type: String
    Description: The name of an extra environment variable available during the build.
    Default: "EXTRA_ARG_2"

  ExtraEnvVal2:
    Type: String
    Description: The default value of this environment variable.
    Default: ""

  ExtraEnvType2:
    Type: String
    Description: |
      The type of this environment variable. For a list of supported values, see
      [AWS::CodeBuild::Project EnvironmentVariable - Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environmentvariable.html#cfn-codebuild-project-environmentvariable-type).
    Default: PLAINTEXT

  ExtraEnvVar3:
    Type: String
    Description: The name of an extra environment variable available during the build.
    Default: "EXTRA_ARG_3"

  ExtraEnvVal3:
    Type: String
    Description: The default value of this environment variable.
    Default: ""

  ExtraEnvType3:
    Type: String
    Description: |
      The type of this environment variable. For a list of supported values, see
      [AWS::CodeBuild::Project EnvironmentVariable - Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environmentvariable.html#cfn-codebuild-project-environmentvariable-type).
    Default: PLAINTEXT

  ExtraEnvVar4:
    Type: String
    Description: The name of an extra environment variable available during the build.
    Default: "EXTRA_ARG_4"

  ExtraEnvVal4:
    Type: String
    Description: The default value of this environment variable.
    Default: ""

  ExtraEnvType4:
    Type: String
    Description: |
      The type of this environment variable. For a list of supported values, see
      [AWS::CodeBuild::Project EnvironmentVariable - Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environmentvariable.html#cfn-codebuild-project-environmentvariable-type).
    Default: PLAINTEXT

  ExtraEnvVar5:
    Type: String
    Description: The name of an extra environment variable available during the build.
    Default: "EXTRA_ARG_5"

  ExtraEnvVal5:
    Type: String
    Description: The default value of this environment variable.
    Default: ""

  ExtraEnvType5:
    Type: String
    Description: |
      The type of this environment variable. For a list of supported values, see
      [AWS::CodeBuild::Project EnvironmentVariable - Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environmentvariable.html#cfn-codebuild-project-environmentvariable-type).
    Default: PLAINTEXT

  ExtraEnvVar6:
    Type: String
    Description: The name of an extra environment variable available during the build.
    Default: "EXTRA_ARG_6"

  ExtraEnvVal6:
    Type: String
    Description: The default value of this environment variable.
    Default: ""

  ExtraEnvType6:
    Type: String
    Description: |
      The type of this environment variable. For a list of supported values, see
      [AWS::CodeBuild::Project EnvironmentVariable - Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environmentvariable.html#cfn-codebuild-project-environmentvariable-type).
    Default: PLAINTEXT

Conditions:
  CreateEcsResources: !Equals [ !Ref CreatesDockerImage, true ]
  ExtraEnvSecMan1: !Equals [ !Ref ExtraEnvType1, SECRETS_MANAGER ]
  ExtraEnvSecMan2: !Equals [ !Ref ExtraEnvType2, SECRETS_MANAGER ]
  ExtraEnvSecMan3: !Equals [ !Ref ExtraEnvType3, SECRETS_MANAGER ]
  ExtraEnvSecMan4: !Equals [ !Ref ExtraEnvType4, SECRETS_MANAGER ]
  ExtraEnvSecMan5: !Equals [ !Ref ExtraEnvType5, SECRETS_MANAGER ]
  ExtraEnvSecMan6: !Equals [ !Ref ExtraEnvType6, SECRETS_MANAGER ]

Resources:
  CodeBuildLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/codebuild/${ProjectName}"

  CodeBuildServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !GetAtt CodeBuildLogGroup.Arn
                  - !Sub "${CodeBuildLogGroup.Arn}:*"
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket*"
                Resource:
                  - !Sub "arn:aws:s3:::${ArtifactBucket}/*"
                  - !Sub "arn:aws:s3:::${ArtifactBucket}"
              - Effect: Allow
                Action:
                  - "codecommit:GitPull"
                  - "codecommit:GitPush"
                Resource:
                  - !Ref RepoArn
              - Effect: Allow
                Action:
                  - "lambda:UpdateFunctionCode"
                Resource: [ '*' ]

  SecretsManagerPolicy1:
    Condition: ExtraEnvSecMan1
    Type: AWS::IAM::Policy
    Properties:
      Roles: [ !Ref CodeBuildServiceRole ]
      PolicyName: SecretsManagerForExtraEnv1
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Ref ExtraEnvVal1

  SecretsManagerPolicy2:
    Condition: ExtraEnvSecMan2
    Type: AWS::IAM::Policy
    Properties:
      Roles: [ !Ref CodeBuildServiceRole ]
      PolicyName: SecretsManagerForExtraEnv2
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Ref ExtraEnvVal2

  SecretsManagerPolicy3:
    Condition: ExtraEnvSecMan3
    Type: AWS::IAM::Policy
    Properties:
      Roles: [ !Ref CodeBuildServiceRole ]
      PolicyName: SecretsManagerForExtraEnv3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Ref ExtraEnvVal3

  SecretsManagerPolicy4:
    Condition: ExtraEnvSecMan4
    Type: AWS::IAM::Policy
    Properties:
      Roles: [ !Ref CodeBuildServiceRole ]
      PolicyName: SecretsManagerForExtraEnv4
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Ref ExtraEnvVal4

  SecretsManagerPolicy5:
    Condition: ExtraEnvSecMan5
    Type: AWS::IAM::Policy
    Properties:
      Roles: [ !Ref CodeBuildServiceRole ]
      PolicyName: SecretsManagerForExtraEnv5
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Ref ExtraEnvVal5

  SecretsManagerPolicy6:
    Condition: ExtraEnvSecMan6
    Type: AWS::IAM::Policy
    Properties:
      Roles: [ !Ref CodeBuildServiceRole ]
      PolicyName: SecretsManagerForExtraEnv6
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Ref ExtraEnvVal6

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket
        Name: !Ref ProjectName
        NamespaceType: NONE
        Packaging: NONE
        EncryptionDisabled: true
      Environment:
        Type: !Ref EnvType
        ComputeType: !Ref EnvComputeType
        Image: !Ref EnvImage
        PrivilegedMode: !Ref CreatesDockerImage
        EnvironmentVariables:
          - Name: REVISION
            Value: !Ref DefaultRevision
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: IMAGE_REPO_NAME
            Value: !Ref ProjectName
          - Name: !Ref ExtraEnvVar1
            Value: !Ref ExtraEnvVal1
            Type: !Ref ExtraEnvType1
          - Name: !Ref ExtraEnvVar2
            Value: !Ref ExtraEnvVal2
            Type: !Ref ExtraEnvType2
          - Name: !Ref ExtraEnvVar3
            Value: !Ref ExtraEnvVal3
            Type: !Ref ExtraEnvType3
          - Name: !Ref ExtraEnvVar4
            Value: !Ref ExtraEnvVal4
            Type: !Ref ExtraEnvType4
          - Name: !Ref ExtraEnvVar5
            Value: !Ref ExtraEnvVal5
            Type: !Ref ExtraEnvType5
          - Name: !Ref ExtraEnvVar6
            Value: !Ref ExtraEnvVal6
            Type: !Ref ExtraEnvType6
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Location: !Ref RepoUrl
        Type: !Ref SourceType
        BuildSpec: !Ref BuildSpec
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  EcsRepo:
    Type: AWS::ECR::Repository
    Condition: CreateEcsResources
    Properties:
      RepositoryName: !Ref ProjectName
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt CodeBuildServiceRole.Arn
            Action:
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"

  EcsPolicy:
    Type: AWS::IAM::Policy
    Condition: CreateEcsResources
    Properties:
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyName: !Sub "${AWS::StackName}_EcsPolicy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "ecr:GetAuthorizationToken"

              # Allow read-only operations on all repositories so that the
              # build can fetch it's dependencies (if any).
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
            Resource:
              - "*"
