name: dependency_test

on:
  push:
    branches: ['*']
  workflow_dispatch:
    branches: ['*']

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.0.1
          - 3.1.4
          - 3.2.5
          - 3.3.7
          - 3.4.10
          - 3.5.10
          - 3.6.15
          - 3.7.13
          - 3.8.13
          - 3.9.13
          - 3.10.5
        boto3:
          - 1.20.31
          - 1.24.33
        sceptre:
          - 2.7.1
          - 3.0.0
        troposphere:
          - 3.2.2
          # - 4.0.2
        pydantic:
          - 1.8.2
          - 1.9.1

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Dump python version
        run: python --version

      - name: Dump pip versions
        run: pip freeze

      - name: Install dependencies
        run: |
          pip install yq cfnresponse \
            boto3==${{ matrix.boto3 }} \
            sceptre==${{ matrix.sceptre }} \
            troposphere==${{ matrix.troposphere }} \
            pydantic==${{ matrix.pydantic }}

      - name: Generate test stacks
        run: test/generate_all.sh

      - name: Compare current output to baselines
        run: test/check_diffs.sh
