name: main

on:
  push:
    branches: ['*']
  workflow_dispatch:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Renaming the workflow reset the github.run_number, so to keep things
      # consecutive, we compute an offset value.
      - name: Set release number
        id: release
        run: echo "::set-output name=release::$(expr ${{ github.run_number }} + 20)"

      - name: Install pip dependencies
        run: pip install -Ur requirements.txt

      - name: Checksum current docs
        run: find . -name readme.md |xargs md5sum >doc.md5

      - name: Generate documentation
        run: bash build/gen_all_docs.sh

      - name: Generate test stacks
        run: test/generate_all.sh

      - name: Compare current output to baselines
        run: test/check_diffs.sh

      - name: Confirm that current docs are committed
        run: md5sum -c doc.md5

      - name: Build template packages
        run: bash build/package_all.sh ${{ steps.release.outputs.release }}

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.release.outputs.release }}
          tag_name: r${{ steps.release.outputs.release }}
          fail_on_unmatched_files: true
          files: packages/*-${{ steps.release.outputs.release }}.zip
